"""add_tokens_used_and_usage_fields

Revision ID: 2bf8b6a0592d
Revises: 17dad5ea1674
Create Date: 2026-01-22 20:24:19.892085

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2bf8b6a0592d'
down_revision: Union[str, Sequence[str], None] = '17dad5ea1674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('metric', sa.String(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_id'), 'usage', ['id'], unique=False)
    op.create_index('ix_usage_user_metric_period', 'usage', ['user_id', 'metric', 'period'], unique=False)
    op.alter_column('agent_messages', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('ix_agent_messages_agent'), table_name='agent_messages')
    op.create_index(op.f('ix_agent_messages_agent_type'), 'agent_messages', ['agent_type'], unique=False)
    op.create_index(op.f('ix_agent_messages_id'), 'agent_messages', ['id'], unique=False)
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('api_keys', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('api_keys', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('research_tasks', 'result',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_research_tasks_id'), 'research_tasks', ['id'], unique=False)
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('subscriptions', 'cancel_at_period_end',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_subscriptions_user_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_id'), 'subscriptions', ['id'], unique=False)
    op.create_unique_constraint(None, 'subscriptions', ['user_id'])
    op.alter_column('url_candidates', 'meta_data',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('url_candidates', 'user_approval',
               existing_type=sa.VARCHAR(length=20),
               server_default=None,
               existing_nullable=True)
    op.drop_index(op.f('ix_url_candidates_approval'), table_name='url_candidates')
    op.create_index(op.f('ix_url_candidates_id'), 'url_candidates', ['id'], unique=False)
    op.create_index(op.f('ix_url_candidates_user_approval'), 'url_candidates', ['user_approval'], unique=False)
    op.alter_column('workflow_states', 'state_snapshot',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=False)
    op.create_index(op.f('ix_workflow_states_id'), 'workflow_states', ['id'], unique=False)
    op.alter_column('workflow_tools', 'input',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('workflow_tools', 'output',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_workflow_tools_id'), 'workflow_tools', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_tools_id'), table_name='workflow_tools')
    op.alter_column('workflow_tools', 'output',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('workflow_tools', 'input',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_workflow_states_id'), table_name='workflow_states')
    op.alter_column('workflow_states', 'state_snapshot',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.drop_index(op.f('ix_url_candidates_user_approval'), table_name='url_candidates')
    op.drop_index(op.f('ix_url_candidates_id'), table_name='url_candidates')
    op.create_index(op.f('ix_url_candidates_approval'), 'url_candidates', ['user_approval'], unique=False)
    op.alter_column('url_candidates', 'user_approval',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'pending'::character varying"),
               existing_nullable=True)
    op.alter_column('url_candidates', 'meta_data',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_constraint(None, 'subscriptions', type_='unique')
    op.drop_index(op.f('ix_subscriptions_id'), table_name='subscriptions')
    op.create_index(op.f('ix_subscriptions_user_id'), 'subscriptions', ['user_id'], unique=True)
    op.alter_column('subscriptions', 'cancel_at_period_end',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('subscriptions', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'active'::character varying"),
               existing_nullable=False)
    op.alter_column('subscriptions', 'plan',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'free'::character varying"),
               existing_nullable=False)
    op.drop_index(op.f('ix_research_tasks_id'), table_name='research_tasks')
    op.alter_column('research_tasks', 'result',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('api_keys', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('api_keys', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('api_keys', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('api_keys', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_index(op.f('ix_agent_messages_id'), table_name='agent_messages')
    op.drop_index(op.f('ix_agent_messages_agent_type'), table_name='agent_messages')
    op.create_index(op.f('ix_agent_messages_agent'), 'agent_messages', ['agent_type'], unique=False)
    op.alter_column('agent_messages', 'meta_data',
               existing_type=sa.Text(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index('ix_usage_user_metric_period', table_name='usage')
    op.drop_index(op.f('ix_usage_id'), table_name='usage')
    op.drop_table('usage')
    # ### end Alembic commands ###
