"""Add category page ranges and category_id to content models

Revision ID: 6193dfbb978c
Revises: c2a861c9a1ac
Create Date: 2026-01-28 18:55:14.569427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6193dfbb978c'
down_revision: Union[str, Sequence[str], None] = 'c2a861c9a1ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('page_start', sa.Integer(), nullable=True))
    op.add_column('categories', sa.Column('page_end', sa.Integer(), nullable=True))
    op.add_column('chunks', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_chunks_category_id'), 'chunks', ['category_id'], unique=False)
    op.create_foreign_key(None, 'chunks', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.add_column('document_formulas', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_document_formulas_category_id'), 'document_formulas', ['category_id'], unique=False)
    op.create_foreign_key(None, 'document_formulas', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    op.add_column('document_tables', sa.Column('category_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_document_tables_category_id'), 'document_tables', ['category_id'], unique=False)
    op.create_foreign_key(None, 'document_tables', 'categories', ['category_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_tables', type_='foreignkey')
    op.drop_index(op.f('ix_document_tables_category_id'), table_name='document_tables')
    op.drop_column('document_tables', 'category_id')
    op.drop_constraint(None, 'document_formulas', type_='foreignkey')
    op.drop_index(op.f('ix_document_formulas_category_id'), table_name='document_formulas')
    op.drop_column('document_formulas', 'category_id')
    op.drop_constraint(None, 'chunks', type_='foreignkey')
    op.drop_index(op.f('ix_chunks_category_id'), table_name='chunks')
    op.drop_column('chunks', 'category_id')
    op.drop_column('categories', 'page_end')
    op.drop_column('categories', 'page_start')
    # ### end Alembic commands ###
