"""Add document_tables and document_formulas tables for Phase 2

Revision ID: 6b8e6d9cc326
Revises: b591da804813
Create Date: 2026-01-21 08:12:51.160368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b8e6d9cc326'
down_revision: Union[str, Sequence[str], None] = 'b591da804813'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document_formulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('formula_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('latex_content', sa.Text(), nullable=False),
    sa.Column('rendered_image_path', sa.String(length=500), nullable=True),
    sa.Column('context_before', sa.Text(), nullable=True),
    sa.Column('context_after', sa.Text(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_formulas_document_id'), 'document_formulas', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_formulas_id'), 'document_formulas', ['id'], unique=False)
    op.create_index(op.f('ix_document_formulas_page_number'), 'document_formulas', ['page_number'], unique=False)
    op.create_table('document_tables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('table_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sa.Integer(), nullable=True),
    sa.Column('table_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('col_count', sa.Integer(), nullable=True),
    sa.Column('extraction_method', sa.String(length=50), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('bbox', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['chunks.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_tables_document_id'), 'document_tables', ['document_id'], unique=False)
    op.create_index(op.f('ix_document_tables_id'), 'document_tables', ['id'], unique=False)
    op.create_index(op.f('ix_document_tables_page_number'), 'document_tables', ['page_number'], unique=False)
    op.alter_column('artifacts', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.add_column('chunks', sa.Column('has_tables', sa.Boolean(), nullable=False))
    op.add_column('chunks', sa.Column('has_formulas', sa.Boolean(), nullable=False))
    op.add_column('chunks', sa.Column('element_references', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_index(op.f('ix_chunks_has_formulas'), 'chunks', ['has_formulas'], unique=False)
    op.create_index(op.f('ix_chunks_has_tables'), 'chunks', ['has_tables'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_has_tables'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_has_formulas'), table_name='chunks')
    op.drop_column('chunks', 'element_references')
    op.drop_column('chunks', 'has_formulas')
    op.drop_column('chunks', 'has_tables')
    op.alter_column('artifacts', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.drop_index(op.f('ix_document_tables_page_number'), table_name='document_tables')
    op.drop_index(op.f('ix_document_tables_id'), table_name='document_tables')
    op.drop_index(op.f('ix_document_tables_document_id'), table_name='document_tables')
    op.drop_table('document_tables')
    op.drop_index(op.f('ix_document_formulas_page_number'), table_name='document_formulas')
    op.drop_index(op.f('ix_document_formulas_id'), table_name='document_formulas')
    op.drop_index(op.f('ix_document_formulas_document_id'), table_name='document_formulas')
    op.drop_table('document_formulas')
    # ### end Alembic commands ###
