"""Add agent_prompt and agent_workflow_id to CrawlJob

Revision ID: 840a8ff75d91
Revises: 4eb28a58edcd
Create Date: 2026-01-29 09:35:26.744760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '840a8ff75d91'
down_revision: Union[str, Sequence[str], None] = '4eb28a58edcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_jobs', sa.Column('agent_prompt', sa.Text(), nullable=True))
    op.add_column('crawl_jobs', sa.Column('agent_workflow_id', sa.Integer(), nullable=True))
    op.alter_column('crawl_jobs', 'max_depth',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('crawl_jobs', 'extraction_method',
               existing_type=sa.VARCHAR(length=50),
               server_default=None,
               existing_nullable=False)
    op.create_index(op.f('ix_crawl_jobs_agent_workflow_id'), 'crawl_jobs', ['agent_workflow_id'], unique=False)
    op.create_foreign_key(None, 'crawl_jobs', 'agent_workflows', ['agent_workflow_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'crawl_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_crawl_jobs_agent_workflow_id'), table_name='crawl_jobs')
    op.alter_column('crawl_jobs', 'extraction_method',
               existing_type=sa.VARCHAR(length=50),
               server_default=sa.text("'auto'::character varying"),
               existing_nullable=False)
    op.alter_column('crawl_jobs', 'max_depth',
               existing_type=sa.INTEGER(),
               server_default=sa.text('2'),
               existing_nullable=False)
    op.drop_column('crawl_jobs', 'agent_workflow_id')
    op.drop_column('crawl_jobs', 'agent_prompt')
    # ### end Alembic commands ###
