"""add celery_task_id to crawl_jobs for progress tracking

Revision ID: cf28c3172e30
Revises: 840a8ff75d91
Create Date: 2026-01-30 12:25:38.639261

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cf28c3172e30'
down_revision: Union[str, Sequence[str], None] = '840a8ff75d91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('crawl_jobs', sa.Column('celery_task_id', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_crawl_jobs_celery_task_id'), 'crawl_jobs', ['celery_task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crawl_jobs_celery_task_id'), table_name='crawl_jobs')
    op.drop_column('crawl_jobs', 'celery_task_id')
    # ### end Alembic commands ###
